### PR TITLE
Javier/overview/create scaffold in product detail

### PR DESCRIPTION
**Pull request by ghost**
Created some scaffolding and placeholder data for product-detail (aka overview).

### CODE REVIEW

**Review by maraquepo — CHANGES_REQUESTED** [review]
It looks like one more blank line is needed on each of the files, looks good aside from that 👍@ProwlingLynx 
Screen Shot 2021-12-27 at 11 22 08 PM

**Review by CptOblivion — COMMENTED** [review]
Got a question about how you plan to structure the component that will have internal state, but other than that it looks good to go!

**Review by CptOblivion — APPROVED** [review]
All set, merge away!

**Review by maraquepo — APPROVED** [review]
Looks good 👍

**Pull request merged**
